// Perguntas padrão — usadas na primeira vez e no botão "Restaurar padrão"
window.BANCO_PADRAO = [
  { p: "Qual é a capital do Brasil?", a: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], c: 2 },
  { p: "Quantos lados tem um triângulo?", a: ["2", "3", "4", "5"], c: 1 },
  { p: "Qual animal é conhecido como 'rei da selva'?", a: ["Tigre", "Leão", "Elefante", "Urso"], c: 1 },
  { p: "Qual é a cor do céu em um dia claro?", a: ["Verde", "Azul", "Vermelho", "Amarelo"], c: 1 },
  { p: "Quantos dias tem uma semana?", a: ["5", "6", "7", "8"], c: 2 },
  { p: "Qual planeta é conhecido como Planeta Vermelho?", a: ["Vênus", "Júpiter", "Marte", "Saturno"], c: 2 },
  { p: "Quanto é 7 × 8?", a: ["54", "56", "58", "64"], c: 1 },
  { p: "Qual é o maior oceano do mundo?", a: ["Atlântico", "Índico", "Ártico", "Pacífico"], c: 3 },
  { p: "Quem escreveu 'Dom Casmurro'?", a: ["Machado de Assis", "José de Alencar", "Graciliano Ramos", "Clarice Lispector"], c: 0 },
  { p: "Em que ano o homem pisou na Lua pela primeira vez?", a: ["1965", "1967", "1969", "1972"], c: 2 },
  { p: "Qual é o elemento químico representado por 'O'?", a: ["Ouro", "Oxigênio", "Ósmio", "Oxalato"], c: 1 },
  { p: "Quem pintou a Mona Lisa?", a: ["Michelangelo", "Van Gogh", "Leonardo da Vinci", "Picasso"], c: 2 },
  { p: "Qual é a moeda oficial do Japão?", a: ["Won", "Yuan", "Iene", "Baht"], c: 2 },
  { p: "Quantos ossos tem o corpo humano adulto?", a: ["196", "206", "216", "226"], c: 1 },
  { p: "Qual é o maior país do mundo em área?", a: ["China", "EUA", "Canadá", "Rússia"], c: 3 },
  { p: "Quem compôs a 'Nona Sinfonia'?", a: ["Mozart", "Bach", "Beethoven", "Chopin"], c: 2 },
  { p: "Qual é o menor país do mundo em área?", a: ["Mônaco", "Vaticano", "San Marino", "Nauru"], c: 1 },
  { p: "Em que ano caiu o Muro de Berlim?", a: ["1987", "1989", "1991", "1993"], c: 1 },
  { p: "Qual é a fórmula química da glicose?", a: ["C6H12O6", "C12H22O11", "CH4", "CO2"], c: 0 },
  { p: "Quem foi o primeiro imperador romano?", a: ["Júlio César", "Nero", "Augusto", "Trajano"], c: 2 },
  { p: "Qual é o rio mais longo do mundo?", a: ["Nilo", "Amazonas", "Yangtzé", "Mississippi"], c: 1 },
  { p: "Quantos corações tem um polvo?", a: ["1", "2", "3", "4"], c: 2 },
  { p: "Qual é o planeta mais quente do sistema solar?", a: ["Mercúrio", "Vênus", "Marte", "Júpiter"], c: 1 },
  { p: "Quem desenvolveu a teoria da relatividade?", a: ["Newton", "Galileu", "Einstein", "Tesla"], c: 2 },
  { p: "Qual é a capital da Austrália?", a: ["Sydney", "Melbourne", "Canberra", "Perth"], c: 2 },
  { p: "Qual é o metal mais condutor de eletricidade?", a: ["Ouro", "Prata", "Cobre", "Alumínio"], c: 1 },
  { p: "Em que país foi inventado o papel?", a: ["Egito", "Grécia", "China", "Índia"], c: 2 },
  { p: "Qual é o maior deserto do mundo?", a: ["Saara", "Gobi", "Antártica", "Kalahari"], c: 2 },
  { p: "Quantas cordas tem um violão clássico?", a: ["4", "5", "6", "7"], c: 2 },
  { p: "Qual é o símbolo químico do ouro?", a: ["Go", "Ag", "Au", "Or"], c: 2 }
];